spring:
  datasource:
    url: jdbc:h2:./persons
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    jdbc:
      dialect: h2
server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
  jetty:
    threads:
      max: 1
#management:
#  endpoints:
#    web.exposure.include: health, info
#  endpoint:
#    health:
#      enabled: true
#      show-details: always
logging:
  level:
    de.detim.njustus.person_db: debug
    org.hibernate.SQL: DEBUG
